executable: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\MARVEL SNAP\\SNAP.exe"
buttons:
    play: 
      x: 0.75
      y: 0.80
      pause: 0.5
    endturn:
      x: 0.93
      y: 0.93
      pause: 0.5
    next:
      x: 0.8
      y: 0.93
      pause: 0.5

commands:
  play_super_good:
    cycle_end_pause: 3.5 #seconds
  restart_snap:
    restart_every: 100  #cycles
  save_state_files:
    save_every: 50 #cycles
    path_to_log_files: "~\\AppData\\LocalLow\\Second Dinner\\SNAP\\Standalone\\States\\nvprod"
